# Based on https://github.com/standardfile/ruby-server/blob/master/docker-compose.yml

version: '3.3'

services:
  standardnotes-server:
    image: serubin/standard-notes-server
    build:
      context: .
      dockerfile: Dockerfile.server
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    environment:
      - RAILS_ENV=production
      - RAILS_SERVE_STATIC_FILES=true
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=standardnotes
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - SECRET_KEY_BASE=$SECRET_KEY_BASE
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=sync.notes.serubin.net"
      - "traefik.frontend.rule=Host: sync.notes.serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=3000"
      - "traefik.default.protocol=http"

    # Wait for database container to start before running the server.
    depends_on:
      - standardnotes-db

  standardnotes-app:
    image: serubin/standard-notes-app
    build:
      context: .
      dockerfile: Dockerfile.app
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always
    networks:
      - default
      - traefik-public
    labels:
      - "traefik.enable=true"
      - "traefik.domain=notes.serubin.net"
      - "traefik.frontend.rule=Host: notes.serubin.net"
      - "traefik.tags=traefik-public"
      - "traefik.docker.network=traefik-public"
      - "traefik.port=3000"
      - "traefik.default.protocol=http"

  standardnotes-db:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
    networks:
      - default
      - traefik-public
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    restart: always

networks:
  traefik-public:
    external: true
